; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:dnesp32s3b]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_upload.flash_size = 16MB
board_build.flash_size = 16MB
board_build.flash_mode = qio
board_build.partitions = partitions.csv
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DBOARD_HAS_PSRAM
	-DCORE_DEBUG_LEVEL=2
	-DU8G2_USE_LARGE_FONTS
	-DU8G2_WITH_UNICODE
lib_deps = 
	bblanchon/ArduinoJson@^7.4.2
	moononournation/GFX Library for Arduino@^1.6.0
	olikraus/U8g2@^2.36.5
